### PR TITLE
[#253] Fix ReasonReact link

### PR DESCRIPTION
**Pull request by Roshanjossey**
- Addresses issue #253

### CODE REVIEW

**Comment by claudiopro** [comment]
@Roshanjossey fix looks good to me. Thanks for taking the time to submit a fix 👍 

As commented on issue #253, there's another broken link on the page https://reasonml.github.io/guide/javascript/quickstart/ (path is https://github.com/reasonml/reasonml.github.io/blob/source/src/pages/guide/javascript/quickstart.md). Can you fix that too?

Could you also change the link to bucklescript.github.io on the same page to https?

**Comment by Roshanjossey** [comment]
@claudiopro, Thank you for that information. Lemme dig in to Gatsby and see what I can do

**Comment by claudiopro** [comment]
FYI I opened https://github.com/gatsbyjs/gatsby/issues/3370

**Comment by Roshanjossey** [comment]
Cool, @claudiopro. I'll try to take a stab at the issue as well

**Comment by chenglou** [comment]
We've started using another architecture, so this problem no longer exists. Closing.
Thanks for the contribution though!

**Comment by claudiopro** [comment]
Oh, Docusaurus. Nice! 😍

**Pull request closed without merging**
