### PR TITLE
Update Faq with link to ocaml manual

### PR DESCRIPTION
**Pull request by kevinsimper**
As a beginner I was confused and was looking for a function to convert a int to string, then found this answer but then had no idea where to find the "standard library". It would be quicker to link to a trusted source to read about the standard library for beginners and see other functions as well.

### CODE REVIEW

**Comment by chenglou** [comment]
Hello! The link is the API page. Was that unclear?

**Comment by kevinsimper** [comment]
Which link? There were none already?

**Comment by cem2ran** [comment]
@kevinsimper Cheng is referring to the API link in the website header menu. This leads to: https://reasonml.github.io/api/index.html wherein you can find the Pervasives module. I don't think it would hurt to include that link.

**Comment by kevinsimper** [comment]
I updated the link to point to the api section instead 😄

@cem2ran thanks a lot! 👍

**Comment by jaredly** [comment]
awesome, sorry for the delay!

**Comment by kevinsimper** [comment]
Thanks @jaredly 😄

**Pull request merged**
