### PR TITLE
Add French 🇫🇷 translation

### PR DESCRIPTION
**Pull request by CharlesMangwa**
Hi folks! After days and nights spent in dozens of dictionaries and hundreds of antique linguistic encyclopaedias: I've finally managed to complete this French translation 🎉. I tried my best to stay reasonably close to the spirit of the original documentation and up-to-date with the latest changes.

Even if I did read it again and again and again, I may have forgotten some typos so: if you happen to speak French, some proofreading would be highly appreciated!

Last but not least: as you can see, I didn't change the initial route (which explains the conflicts). I couldn't figure what's the best way to obtain a `https://reasonml.github.io/fr/` URL, given that I've changed files almost everywhere (not only in `/src/pages`): any idea?

If you want to take a glimpse at the final result, it's right there: [https://reasonml-fr.surge.sh](https://reasonml-fr.surge.sh)

### CODE REVIEW

**Comment by chenglou** [comment]
I speak French =)

This looks nice so far! Thank you so much. I think I'll dedicate some time to the translation infra, and then merge this.

Great work!

**Comment by CharlesMangwa** [comment]
My pleasure! I learned so much while doing this: it's definitely a win-win situation. Glad to see that you speak French, though! It'll probably be easier for corrections & future modifications.

**Comment by ubsan** [comment]
One issue: on the main page, and in the JS quick start guide, you have `rpm run watch` instead of `npm run watch`

**Comment by CharlesMangwa** [comment]
@ubsan Thanks! Just corrected it!

**Comment by ubsan** [comment]
Oh, also, the links are incorrect - `Démarrer` should probably lead to the Javascript quick start guide, like it does in the English page, and `En savoir plus` should likely lead to the full guide, as opposed to the three link page.

**Comment by ubsan** [comment]
(other than the few minor errors, thank you so much :heart:)

**Comment by CharlesMangwa** [comment]
Corrected and updated!

**Comment by CharlesMangwa** [comment]
Fixed and updated! Thanks for the love ^^

**Comment by lpalmes** [comment]
This is awesome, congratulations!
I'm working on the spanish translation and i've added an `es/` folder under `src/pages`, and modified this [regex](https://github.com/lpalmes/reasonml.github.io/blob/513737754c10a283cd7ef49f6296b6aee4c7369c/gatsby-node.js#L27) to accept files from the `es`, so spanish docs would be available in https://reasonml.github.io/es.

**Comment by chenglou** [comment]
Small update: @rickyvetter is still working on the translation infra. Sorry for the wait.

**Comment by rickyvetter** [comment]
@CharlesMangwa and I talked about this offline. This version of the translation is *especially* complete and will conflict with our current infra. In #171 I add a picker which navigates to the fully-French version at https://reasonml-fr.surge.sh/. @CharlesMangwa will upstream that navigation element into the surge version to allow people to navigate back. I'm closing this PR as it doesn't allow for multiple languages to co-exist.

This will incur a heavy maintenance cost short term because every change brings the fork further from the original and requires extra work to rebase and avoid conflict. Working on a better long term solution now.

**Comment by chenglou** [comment]
Ok good. I like this approach. Thanks for the work @CharlesMangwa. Hopefully Ricky hurries up and make our translation infra up to par with what you did here. Then we can remove the fork

**Pull request closed without merging**
