### PR TITLE
Discussion: Value statement

### PR DESCRIPTION
**Pull request by alavkx**
## Goal
Describe the problems that Reason solves delivers in a jargon free manner, while not sound like snake oil. I will provide talking points that derive from the discord conversation below.

<details>
<summary>Discord conversation</summary>
> ryyppyToday at 1:43 AM

The Reason landing page could be much... wayyyy much better. I mean it hasn't changed literally for 3 years. Reason should mainly focus on the JS part and build the docs around that preposition. In that manner you could really explain the benefits when using Reason(React) over JS etc

> the__spyderToday at 3:34 AM

At least the ReasonML front page does mention ocaml

> ryyppyToday at 3:46 AM

it doesn't mention react
for me that's the main selling point

> fhamToday at 3:56 AM

Hm, that's debatable.
Even Ruby which still has Rails as its "Killer Application", does not mention Rails on its frontpage.
Although if you don't mean the description of the language, but the whole frontpage, I agree wholeheartedly.
It could be like the Rust frontpage where it mentions what you can build with it.

> ryyppyToday at 4:00 AM

whom is the landing page designed for? who is the target audience, and more importantly, who is the biggest potential group of customers?
what problem except "type safetiness and pattern matching" does the language solve?
as soon as you know that, you can design answers to painful questions. Like, there are so many devs out there fighting with TS / Flow / Redux codebases and they know they are in a messy situation with all their action creators etc... how can Reason / ReasonReact help them relieve that pain? Now pair that with good instructions that you can gradually opt in with genType, and you get some interest
In case of Rust, the language knows exactly how it is defined and how it should be used and therefore designed the call to actions accordingly

>lesspToday at 4:41 AM

I think it's important that the native opportunities are not hidden though! Apart from React I'd say the most popular projects are native (Revery, Oni2, fnm etc)

> tsnobipToday at 6:31 AM

The build in rust image is perfect, the value and use cases are just obvious

> johnridesabikeToday at 6:33 AM

I think that, in general, Reason definitely could use some more public-relations expertise. Getting better docs up is a big step to help people use it, but there's also lots of little things like this
See also: how many people think that Reason is dead because they check the blog and see it hasn't updated in 2 years

> tsnobipToday at 6:36 AM

This is ridiculous, I have to say that I was hesitant to jump to Reason at the beginning because of this

> TomiSToday at 7:26 AM

Just to get the ball rolling :upside_down: 

Build it in ReasonML:
- Business Critical Web Apps
Use React with other modern tools but with the power of absolute type safety. Improve, iterate and refactor fast with immediate rebuilds. Improve your architecture with language features you don't even know to dream about in your current web development environment.

- Multiplatform Desktop Apps

Want to make real desktop apps but only have web developer skillset? Worry no more. With ReasonML native multiplatform cross compilation and innovative frameworks like Revery, you can make real desktop apps without the pain usually familiar to native developers, like slow build times and weird null pointer errors.

- Stable Mobile Apps

In mobile there is no refresh button. You really don't want your app to crash, at least not to type errors. With Reason you're enabled to use the familiar React Native platform, but with the stability of ReasonML.

>tsnobipToday at 7:28 AM

that's pretty cool!

> the__spyderToday at 7:43 AM

Hot take: if you’d like to see more blog posts, write one :thinking:

https://github.com/reasonml/reasonml.github.io/tree/source/website/blog
GitHub
reasonml/reasonml.github.io
Reason's documentation site. Contribute to reasonml/reasonml.github.io development by creating an account on GitHub.

> yuntiMcguntiToday at 7:46 AM

Hmmm I'm not sure that's an option for the community to write a blog post for the official reason site. It's been mentioned a lot of times in here that there should be an update on it as people often come in asking is reason dead (or post in twitter), but that suggestion hasn't been taken up unfortunately
At least we now have a message on the github site saying these aren't the recent releases https://github.com/facebook/reason/releases
GitHub
facebook/reason
Simple, fast & type safe code that leverages the JavaScript & OCaml ecosystems - facebook/reason

It's a shame the ocamlscript name was taken at the time (think it's free now) when naming bucklescript that would have made it a lot clearer what it does. And marketing reason as a familiar syntax for ocaml would make things more obvious too.

>Et7f3Today at 7:48 AM

https://discordapp.com/channels/235176658175262720/469417973820686336/671464785313005597
What is ocamlscript ?

> yuntiMcguntiToday at 7:49 AM

Hongbo originally was thinking of calling bucklescript ocamlscript but the name was taken at the time, I think it the end it just died away without becoming anything
bob mentioned it in here at one point
Et7f3Today at 7:50 AM
BuckleScript in two letter bs OCamlScript ... ocs sound like a reserved name

> johnridesabikeToday at 8:28 AM

While we’re brainstorming ideas for the front page blurb, I think it would also be good to have a clearer explanation somewhere about the relationship between OCaml, Reason, BuckleScript, and ReasonReact

>lmaoToday at 8:44 AM

I’m still of the opinion that BS and RE sites should be the same heheh

> tsnobipToday at 8:46 AM

I agree with you

>lmaoToday at 8:46 AM

it’s a big migration to merge the two but i think it’ll be pretty valuable
i know this is more contentious with ocaml folks than js
bucklescript the project should even be under some kind of reason org

>yuntiMcguntiToday at 8:48 AM

I'm not so sure on merging bucklescript and reason. I think that's makes it more confusing for those interested in native, it could make it appear reason only targets js
It probably makes more sense the reason front page and ocaml front pages linking in to each other.  and then both of those referencing bucklescript (and jsoo)

>lmaoToday at 8:49 AM

i think it should be primarily marketed for the web. native adoption will come for free when web adoption rises

>yuntiMcguntiToday at 8:50 AM

I think the web is a much bigger market to tackle and far more likely to bring way more people in, but I get the impression the facebook team is keener on native these days
(that's just my inference, it may be completely untrue)

>lmaoToday at 8:51 AM

ya the projects aren’t exactly community owned

>TomiSToday at 8:53 AM
@johnridesabike Maybe some sort of diagram?

>lmaoToday at 8:53 AM

in jordan’s talk this year he spoke about aggressively removing friction for first time users (iirc). focusing on first time user experience being as soon as intuitive as possible will be paramount for adoption
all these namespaces aren’t helping
i diagram is a bandaid, but it definitely helps
i think of it similar to how a good teacher will deliberately hide nuances when introducing a topic
nuances serve no value to a learner just coming in to a domain. 90% of the value is not in the details. when you are teaching an algebra 1 or a physics 1, engagement and building interest is most important
which is why i feel we should favor hiding as many nuances possible from a first time user
elm doesn’t have “tree-platform”
it’s just elm

>TomiSToday at 8:58 AM

Personally I'd (also) hide bucklescript to background. It's a tool after all, though important one. Reason is a marketable name. BuckleScript and OCaml are not really.

>yuntiMcguntiToday at 8:58 AM
I prefer [img]

>lmaoToday at 8:58 AM

ocaml is almost a dirty word to JS devs and people with OO backgrounds

>yuntiMcguntiToday at 8:59 AM

True closer to the truth though.  If they don't like functional I don't think you are ever going to fool them

>lmaoToday at 8:59 AM

i’ve found everyone i’ve mentioned it to’s face get all twisted when i mention it
it simply won’t be a selling point
that’s fair.
i don’t even think functional should be a selling point

>yuntiMcguntiToday at 9:00 AM

What do you think the key message of reason is?

>lmaoToday at 9:00 AM

business value

>yuntiMcguntiToday at 9:00 AM

business value in what sense?

>TomiSToday at 9:01 AM

Stability and predictability?

>yuntiMcguntiToday at 9:01 AM

Yup that's fair
How do you get that I suppose the next question would be from people
Immutability, sound type system?

>lmaoToday at 9:01 AM

business words
predictability
fast feedback

>yuntiMcguntiToday at 9:02 AM

Fast feedback is key, and often overlooked
lmaoToday at 9:02 AM
enjoyable refactoring
and if we are speaking business value, maintainable worry free systems
pitch guarantees not type safety

>yuntiMcguntiToday at 9:03 AM

Yup refactoring is massive for me this is one of the key things

>lmaoToday at 9:03 AM

type safety isn’t something that get dynamic programmers i@retested
the leading words are business value, and how this will make you enjoy your job more

>yuntiMcguntiToday at 9:04 AM

Ok so what would a typical 6 word strap line on the reason home page be?

>lmaoToday at 9:04 AM

the follow questions are the hard post honestly
how can we convincingly describe the business value with specifics
i wouldn’t consider myself an articulate writer for taglines

>TomiSToday at 9:05 AM

One business related thing to tackle is to convince Reason is future proof. Business people don't necessarily worry about the tech. They worry about ecosystem continuity. Will Reason be here in 5 years? How to hire people etc?

>yuntiMcguntiToday at 9:05 AM

Probably me neither I was hoping one you might be inspired :slight_smile:

>lmaoToday at 9:06 AM
selling the joy of the language without sounding like snake oil is nuanced

>yuntiMcguntiToday at 9:06 AM

Ocaml will certainly be here in 5 years, the reason syntax a bit more risky but I think v likely. It's already been going for ~4+
lmaoToday at 9:07 AM
when i get to my desk i’ll open a wip pr on the site and we can iterate on the details

>ryyppyToday at 9:11 AM

a brainstorming issue would be great

>AlexanderToday at 9:32 AM

Really like the discussion going on here! 100% on the confusion that all the different names and sites cause. My first week of Reason was spent figuring out the difference between Reason, OCaml, ReasonReact, BuckleScript, etc. Thankfully the discord community was really helpful but I can see a lot of people not finding discord and just giving up with something like "Why do I need to learn Reason, and this thing called BuckleScript?"
The way I'm selling Reason internally is that given the complex application it's going to be used in it'll be an asset in fixing some of the issues we're running into now.

Many of those are caused by Drupal/PHP, but showing that it[s type system] can be used to scale to many contributors and changing things on one end of the system without having everything at the other end fall over is a very strong point.
The direct competitors for Reason from our perspective are TypeScript and Flow. However, even though they can help us with similar needs, they're an addition to JavaScript instead of a full-on replacement. This means that they'll always have some gaps where trade-offs need to be made and you can never be 100% sure. Reason can give you those guarantees that when your types are right, your program will be too*.

The fact that we always have an escape-hatch to JavaScript for where the ecosystem of Reason is not yet ready also really helps selling it.

>Et7f3Today at 9:39 AM

Maybe add some links like this https://codeburst.io/inference-engines-5-examples-with-typescript-flow-and-reason-edef2f4cf2d3 or https://dev.to/yawaramin/typing-and-code-flow-in-typescript-and-reasonml-2paj
</details>

## Questions for you to answer
1. Whom is the landing page designed for? Who is the target audience, and more importantly, who is the biggest potential group of customers?
1.  For the new user, which tool system relationships (BS, OCaml, ReasonReact, etc...) are important to understand? Which relationships _aren't_ important and should be hidden?
1. What 3-5 problems does Reason solve problems that you experience in a typical JS or TS codebase?

## Deliverables
Once we come to some kind of consensus, I'd be happy to make the necessary code changes to get this in master. If there is tangential discussion surrounding larger eco-system changes, I'll open a similar discussion in the appropriate repo(s) and leave a link.

### Related to #588

### CODE REVIEW

**Comment by alavkx** [comment]
I'll go first.

## Whom is the landing page designed for? Who is the target audience, and more importantly, who is the biggest potential group of customers?

Javascript devs.

>What 3-5 problems does Reason solve problems that you experience in a typical JS or TS codebase?

1. Unlock your flow state
A type safe compiler means that programming becomes fluid. When the feedback loop is tightened to milliseconds, writing software feels more like jamming on an instrument. Pragmatic language design decisions like [`Object.magic` and `bs.raw`](https://reasonml.github.io/docs/en/interop) means you can escape the puzzle when things just aren't clicking. **Remain productive.**

1. Reclaim your working memory
A language based on [expressions](https://stackoverflow.com/questions/18443801/in-programming-what-is-an-expression) encourages a programming style that allows you to understand your code _without_ jumping around your filesystem. Don't more holding the stack in your head. Use those freed resources to **solve real business problems**.

1. Fearlessly refactor and delete code
**Rely on the tool** to dot your i's and cross your t's. You're no longer responsible for carefully grepping your codebase to find all of the affected codepaths. Make your move and the compiler will guide you the whole way.

1. Migrate seamlessly
Use your existing JS tools and libraries right in your Reason code. Create types for only what you need when you need it. Explore existing community bindings on [Redex: Reason Package Index](https://redex.github.io/)


## For the new user, which tool system relationships (BS, OCaml, ReasonReact, etc...) are important to understand? Which relationships aren't important and should be hidden?

### If we are pitching as a JS solution, why is Bucklescript not `reasonml/compiler`(see: [`elm/compiler`](https://github.com/elm/compiler))? 
We should align ourselves as a target for the web platform, and use qualifiers when speaking about "reason-native" to simplify the discussion for the richer ecosystem.

### Is leading with "Built on the OCaml compiler" actually attractive to JS devs? Do they even know what OCaml is? 
In my experience, it isn't. It's not even attractive to my coworkers that write elixir full time. This is 1 less thing the new user should care to know. The value prop that Reason is built on a stable compiler is _good_. But it should be presented assuming the listener doesn't value OCaml the same way as veterans of the ecosystem may. 
Maybe refine to something like—
> ReasonML is a javascript flavored syntax built on [a stable, robust compiler](https://ocaml.org/).

Here, OCaml isn't mentioned, but is included as a link to allow the user to learn more _if they wish_.

**Comment by Et7f3** [comment]
Comment from @ryyppy
> because BuckleScript is like JavaScript with Security belts on?

I like the idea it should be on the BuckleScript main page. Maybe is their another issue BS landing page.

**Comment by ryyppy** [comment]
I guess my statement was a little bit weird, and something a TS user would easily shrug off (it's basically TS' tagline). The main benefits of the language are no weird `any`, `mixed`, `unknown` types and a better feedback loop with compiler speed in medium to big JS codebases. 

Potentially Reason + BuckleScript should be one landing page, since both together deliver the value for JS devs IMO.

I really like what you drafted out here @alavkx!

Keeping OCaml out of the equation for beginners is crucial. Making the user aware that it is built on a really fast compiler with good type guarantees is enough to know. If they wanna know more, we can totally provide the right content to get them going with OCaml and expose all the advanced stuff.

One thing I am missing here is how we can tackle quite specific problems.

- E.g. how can Reason help with overengineered redux codebases?
- Maybe make ppl interested by telling them that you don't need to wrangle import / exports / index.js files anymore?
- Maybe make them reflect on some past experience, as when they had to debug a huge codebase and the only type suggestion they got was `Promise<any, any, any, any>` or `{ data: Array<mixed>` or whatnot ...
- Throw in untypable styled-components, because we all know this is fun to type all those redundant `ReactComponent<MyStyledProps>` in there everywhere and have absolutely no idea what's going to work

Something ppl find painful and pretty much do in a regular basis, day by day.

**Comment by alavkx** [comment]
> how can Reason help with overengineered redux codebases?

This is 99% of my desire to move to Reason.

> Maybe make ppl interested by telling them that you don't need to wrangle import / exports / index.js files anymore?

Seems pretty tribal for most people. The pitch is hit or miss depending on the person's team. It's really a _feel the difference_ kinda thing. I wasn't sure if I'd like it either but the name-spacing that you fall in to makes for super readable code.

> Demonstrate how Reason easily handle the compiling process of a 100-components-React project while hot-reloading in 1 sec instead of 40

_Demonstrating_ speed is definitely something we should work in. It can be tough to communicate the impact with text. Although, quoted examples from reputable teams/projects could work.

> Reason really shines with complex business logic and decision trees! Maybe @cknitt can provide some insights here on how complex data structures can get out of hand with TS / Flow based intersection types

100%. A spicy vector to express some parts of the power is a state machine example.
I've posted an example in https://github.com/reasonml/reasonml.github.io/pull/588#discussion_r379925696
but this example is a little too intimidating for the front page.

[PlayerMachiner.re](https://sketch.sh/s/XcxUxtZ7ofU22ppuvM48x3/)
```reason
type track = int;
type status = 
  | Playing(track)
  | Paused(track)
  | Stopped;
type event =
  | Play(track)
  | Resume
  | Pause
  | Stop;

let send = (event, status) => 
  switch(status, event) {
    | (_, Play(track)) 
    | (Playing(track), Resume)
    | (Paused(track), Resume) => Playing(track)
    | (Paused(track), Pause)
    | (Playing(track), Pause) => Paused(track)
    | (Paused(track), Stop)
    | (Playing(_), Stop)
    | (Stopped, (Stop|Pause|Resume)) => Stopped
  };
  
 Stopped
  |> send(Play(0)) /* => Playing(0) */
  |> send(Pause)   /* => Paused(0) */
  |> send(Resume)  /* => Playing(0) */
  |> send(Stop);   /* => Stopped */
```

**Comment by cknitt** [comment]
> Maybe make ppl interested by telling them that you don't need to wrangle import / exports / index.js files anymore?

This one is actually huge in practice!

My top 3, together with a short catchphrase for each, would be:

* 100% Type Coverage ("fearlessly refactor")
* Module System ("no more import/export hell")
* Variants and Pattern Matching ("supercharged switch statements and reducers")

Then there is the fact that developing in Reason somehow guides you towards simpler, more robust solutions (as opposed to the "overengineered redux codebases" mentioned by @ryyppy). This will be hard to explain though if you have not experienced it yourself.

**Comment by alavkx** [comment]
This discussion didn't get the traction I was hoping for.

**Comment by ryyppy** [comment]
@alavkx I think it's a valuable thread. The implementation of a new landing page will happen on reasonml.org, so i will cross reference this for now

**Pull request closed without merging**
