### PR TITLE
Add auditless as a reason-ml user

### PR DESCRIPTION
**Pull request by Pet3ris**
Hi Team,

Thanks for building Reason!

This PR adds Auditless to the teams using Reason list (it's used in the core debugger/ui).
- logo
- entry in `siteConfig.js`

### CODE REVIEW

**Comment by cristianoc** [comment]
Welcome!

**Comment by Pet3ris** [comment]
Hi @cristianoc, thanks for merging, I notice that the `svg` is not rendering on the website (it's rendering with a local `yarn && yarn start` build).

Are there any `svg` minimization policies on your domain that could be changing it?

Basically the 2 modifications that end up making the `svg` invisible are:

- The field `mask-type=alpha` is removed
- The variable `path.d` is changed from `M460 0H0V104H460V0ZM271 16.5L183.5 45V38.5L231.5 22.5L271 16.5Z` to `M460 0H0V104H460V0ZM271 16.5L183.5 45V38.5L231.5 22.5L271 16.5Z`.

If you're using a particular svg optimization library, I'm happy to reach out to them directly with this example.

**Comment by Pet3ris** [comment]
Meanwhile I've issued a simple fix that removes the mask and replaces with a path-based equivalent svg: https://github.com/reasonml/reasonml.github.io/pull/577.

**Comment by cristianoc** [comment]
Not sure.
@chenglou @rickyvetter

**Comment by chenglou** [comment]
The Docusaurus (which we use) issue I can find is https://github.com/facebook/docusaurus/pull/1663

But whatever =/. Sorry for the trouble and thanks for the change

**Pull request merged**
