### PR TITLE
Add DevITjobs as a user

### PR DESCRIPTION
**Pull request by MariaAbadi**
Hi, I would like to add DevITjobs as they also use ReasonML

### CODE REVIEW

**Comment by MariaAbadi** [comment]
Hi @canadaduane @joefiorini do you might having a look? :)

**Comment by MariaAbadi** [comment]
@ryyppy - could you check it out? :)

**Comment by MariaAbadi** [comment]
@chenglou  @kyldvs @rickyvetter could you please merge it? 😊

**Comment by ryyppy** [comment]
Hey @MariaAbadi.
We are not involved with the Reason project anymore, since BuckleScript (+ Reason's JS sentiment) are now called [ReScript](https://rescript-lang.org). They are basically two separate projects with different goals now.

Reason continues to follow the native compilation story, whereas ReScript continues to be the best compile-to-JS language on the market. More infos on the rebrand [here](https://rescript-lang.org/blog/bucklescript-is-rebranding).

In case your company uses ReScript to build Websites / services with JS, you can open a ticket on our [rescript-lang.org issue tracker](https://github.com/rescript-association/rescript-lang.org/issues), and we will reach out to you as soon as we launched our new landing page.

**Pull request closed without merging**
