### PR TITLE
Add documentation on record interop with javascript

### PR DESCRIPTION
**Pull request by Gregoirevda**
When  using a js function from an external package that is expecting an object as param, you can't pass him a Record.
Explain how to handle that

### CODE REVIEW

**Comment by chenglou** [comment]
Thanks! I've tweaked the example a bit.

**Comment by Gregoirevda** [comment]
Great!
So { "prop": "value" } === [%bs.obj { prop: value }] 

btw, I sometimes see  [%bs.obj { prop: value }]  and sometimes  [%bs.obj { prop= value }] 
(: vs =) what's the difference?

**Comment by chenglou** [comment]
The latter isn't valid. You're probably thinking of OCaml syntax?

**Comment by Gregoirevda** [comment]
Yes, I saw the latter one in Bucklescript documentation. Ok, so it's reasonML vs OCaml syntax. Though it might be assignment vs type someting like that

**Pull request merged**
