### PR TITLE
Guide Russian translation

### PR DESCRIPTION
**Pull request by slonoed**
I started to translate guide. Only JS part done at this moment.
Because this PR contains only MD files in subdir, it can be merged easily.

Also I have troubles with index.js file. It doesn't have some props.
I hope someone can help with this.

### CODE REVIEW

**Comment by chenglou** [comment]
This is freaking great; but lemme take an extra day to finish a revamp I've been doing. Sorry for the trouble!

**Comment by slonoed** [comment]
@chenglou hi! Have you finished what you planned?

**Comment by chenglou** [comment]
Sorry for the wait! I'll be done this weekend =) Trying to hurry up

**Comment by chenglou** [comment]
@slonoed hey! Sorry for the wait. I'm finally done!

**Comment by slonoed** [comment]
@chenglou as I understand you changed almost all docs.
What do you think: is better to check diffs and make similar diffs in my code or just start from scratch?

**Comment by chenglou** [comment]
Probably better from scratch. Sorry about that

**Pull request closed without merging**
