### PR TITLE
Add padding to left of h1 and list during the Api index.html generation

### PR DESCRIPTION
**Pull request by mikeLspohn**
I wasn't sure if I should push with the pages all rebuilt with the change so I just pushed the change in `transform.js` for now. Here's a screenshot of what the changes look like:
screen shot 2017-10-20 at 10 23 21 am

### CODE REVIEW

**Comment by chenglou** [comment]
Looks good! Go ahead

**Comment by chenglou** [comment]
Alllright, is it done?

**Comment by mikeLspohn** [comment]
Sorry, yep should be good to go!

**Comment by chenglou** [comment]
Cool, merging. Thanks =)

**Pull request merged**
