### PR TITLE
feat: onechronos logo

### PR DESCRIPTION
**Pull request by klittlepage**
Added logo for OneChronos (https://www.onechronos.com) as a ReasonML user.

### CODE REVIEW

**Comment by davesnx** [comment]
Hey @klittlepage, are you still interested in adding your logo?

**Comment by klittlepage** [comment]
Yi @davesnx , yes please! We're still industrial ReasonML users. Thanks, Kelly

**Comment by davesnx** [comment]
Nice, are you guys using Melange?

**Comment by klittlepage** [comment]
Thanks! We're excited for Melange but have yet to use it in prod. Generally speaking, most of our use is backend/native.

**Comment by davesnx** [comment]
Nice, I wanted to ask :P

Let me know if you have some feedback and feel free to come by our Discord!

**Pull request merged**
